/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_appsync_graphqlEndpoint": "https://5juyvxleqjefljv3yqqtmmt3vi.appsync-api.ca-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "ca-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ykhnmwxv2rb3lbhzcjbamum6li",
    "aws_cognito_identity_pool_id": "ca-central-1:3efc8f99-5e2b-4b0d-ba10-8120a2d4ed3f",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_0nHiiCvq9",
    "aws_user_pools_web_client_id": "7vvq6h8cn34rmn4vpkho1mkjp0",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "adamdemo-e4cd5d5b223944-staging",
    "aws_user_files_s3_bucket_region": "ca-central-1"
};


export default awsmobile;
